config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  
  resources :people
  resources :notes
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :person
end

app/models/person.rb
class Person < ApplicationRecord
  has_many :notes, dependent: :destroy

  def full_name
    "#{self.first_name} #{self.last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def index
    @notes = Note.all
  end

  def show
    @note = Note.find(params[:id])
  end

  def new
    @person = Person.find(params[:id])
    @note = @person.note.new
  end
  
  def edit
    @note = Note.find(params[:id])
  end

  def create
    @note = Note.new(notes_params)

    if @note.save
      redirect_to notes_path
    else
      render :new
    end
  end

  def update
    @note = Note.find(params[:id])

    if @note.update(notes_params)
      redirect_to note_path(@note.id)
    else
      render :edit
    end
  end

  def destroy
    Note.find(params[:id]).destroy
    redirect_to notes_path
  end

  private
    def notes_params
      params.require(:note).permit(:title, :content, :author)
    end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    @people = Person.all
  end

  def show
    @person = Person.find(params[:id])
    @notes = Note.where(person_id:[:id])
  end

  def new
    @person = Person.new
  end

  def create
    @person = Person.new(people_params)

    if @person.save
      redirect_to people_path
    else
      render :new
    end
  end

  def edit
    @person = Person.find(params[:id])
  end

  def update
    @person = Person.find(params[:id])

    if @person.update(people_params)
      redirect_to people_path
    else
      render :edit
    end
  end

  def destroy
    Person.find(params[:id]).destroy
    redirect_to people_path
  end

  private
    def people_params
      params.require(:person).permit(:first_name, :last_name, :age, :hair_color, :eye_color, :gender, :alive)
    end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_navbar.html.erb
<%= link_to 'Home', root_path %>
<%= link_to 'People', people_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PeopleApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/notes/edit.html.erb
<h1>Edit Note</h1>
<%= form_for @note do |f| %>
  <%= f.label :body %>
  <%= f.text_area :body %>

  <%= f.submit %>
<% end %>

app/views/notes/index.html.erb
<h1> Notes </h1>
<p><%= link_to "New Note", new_note_path %></p>
<% @notes.each do |note| %>
  <h2><%= note.body %><h2>
  <%= link_to "Show Note", note_path(note) %>
  <%= link_to "Edit Note", edit_note_path(note) %>
  <%= link_to 'Destroy Note', note, method: :delete %>
<% end %> 

app/views/notes/new.html.erb
<h1>New Note</h1>
<%= form_for @note do |f| %>
  <%= f.label :body %>
  <%= f.text_area :body %>

  <%= f.submit %>
<% end %>

app/views/notes/show.html.erb
<p><%= @note.body %></p>
<p><%= @note.person %></p>
<%= link_to "Back", notes_path %>

app/views/people/_person_form.html.erb
<%= form_for @person do |f| %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>

  <%= f.label :last_name %>
  <%= f.text_field :last_name %>

  <%= f.label :age %>
  <%= f.text_field :age %>

  <%= f.label :hair_color %>
  <%= f.text_field :hair_color %>

  <%= f.label :eye_color %>
  <%= f.text_field :eye_color %>

  <%= f.label :gender %>
  <%= f.text_field :gender %>

  <%= f.label :alive %>
  <%= f.text_field :alive %>

  <%= f.submit %>
<% end %>

app/views/people/edit.html.erb
<h1>Edit Person</h1>
<%= render "people/person_form" %>

app/views/people/index.html.erb
<h1>People</h1>
<p><%= link_to "New Person", new_person_path %></p>
<% @people.each do |person| %>
  <h2><%= person.full_name %></h2>
  <%= link_to "Show Person", person_path(person) %>
  <%= link_to 'Edit Person', edit_person_path(person) %>
  <%= link_to 'Remove Person', person, method: :delete %>
<% end %>

app/views/people/new.html.erb
<h1>New Person</h1>
<%= render "people/person_form" %>

app/views/people/show.html.erb
<h1><%= @person.full_name %></h1>
<p>age: <%= @person.age %></p>
<p>hair color: <%= @person.hair_color %></p>
<p>eye color: <%= @person.eye_color %></p>
<p>gender: <%= @person.gender %></p>
<p>alive: <%= @person.alive %></p>
<p>notes: 
  <% @notes.each do |note| %>
    <h2><%= note.body %><h2>
    <%= link_to "Show Note", note_path(note) %>
    <%= link_to "Edit Note", edit_note_path(note) %>
    <%= link_to 'Destroy Note', note, method: :delete %>
  <% end %> 
</p>
<p><%= link_to "New Note", new_note_path %></p>
<%= link_to "Back", people_path %>

app/views/static_pages/home.html.erb
<h1>Home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>